apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName | default .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.appName | default .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.appName | default .Chart.Name }}
    spec:
      containers:
        - name: {{ .Values.containerName | default .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- if .Values.volumeMounts }}
          volumeMounts:
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}
          envFrom:
            - secretRef:
                name: secrets-devops
          env:
            {{- range $secretName, $secretConfig := .Values.secrets }}
              {{- if $secretConfig.enabled }}
                {{- range $key, $value := $secretConfig.data }}
                  - name: {{ $key | upper | replace "." "_" }}
                    valueFrom:
                      secretKeyRef:
                        name: {{ $secretConfig.name }}
                        key: {{ $key | replace "." "_" }}
                {{- end }}
              {{- end }}
            {{- end }}
      {{- if .Values.volumes }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- if .hostPath }}
          hostPath:
            path: {{ .hostPath.path }}
            {{- if .hostPath.type }}
            type: {{ .hostPath.type }}
            {{- end }}
          {{- end }}
          {{- if .persistentVolumeClaim }}
          persistentVolumeClaim:
            claimName: {{ .persistentVolumeClaim.claimName }}
          {{- end }}
        {{- end }}
      {{- end }}