{{- range .Values.secrets }}
  {{- if .enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name | default (printf "%s-%s" $.Values.appName .name) }}
type: Opaque
data:
  {{- range $key, $value := .data }}
  {{ $key | replace "." "_" }}: {{ $value | b64enc }}
  {{- end }}
---
  {{- end }}
{{- end }}